{% set name = "pygaul" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygaul-{{ version }}.tar.gz
  sha256: cb31a63cf63865885daa6b0bb0a15d0122074d3d55a6baedbbc163ab6a80e015

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.14
    - pandas
    - earthengine-api
    - pyarrow

test:
  imports:
    - pygaul
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygaul/
  summary: Easy access to administrative boundary defined by FAO GAUL from a Python script.
  dev_url: https://github.com/12rambau/pygaul
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - 12rambau
