{% set name = "pygaul" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygaul-{{ version }}.tar.gz
  sha256: 9e329df0249f43bf901af87ef125f269a49731f1cc4c7cd15883417d4f7c9804

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.14
    - pandas
    - earthengine-api
    - pyarrow

test:
  imports:
    - pygaul
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pygaul/
  summary: Easy access to administrative boundary defined by FAO GAUL from a Python script.
  dev_url: https://github.com/gee-community/pygaul
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - 12rambau
